export const projects = [
  {
    role: "Full-Stack Developer",
    company: "NoxAlgo LLP",
    duration: "March 2025 - Present",
    keyAchievements: [
      "Built healthcare SaaS features for patient engagement and clinical dashboards.",
      "Improved dashboards for 50k+ records/month, boosting efficiency by 40%.",
      "Reduced UI latency by 60% with virtualization and better state management.",
    ],
    techStack: [
      "React",
      "Redux",
      "Axios",
      "Chart.js",
      "Postgre",
      "MongoDB",
      "Express",
      "Nodejs",
      "jest",
      "webhook",
      "JWT/OAuth",
    ],
    color: "#101314",
  },
  {
    role: "Front-End Developer",
    company: "NoxAlgo LLP",
    duration: "January 2024 - September 2025",
    keyAchievements: [
      "Developed real-time logistics dashboards for shipment and fleet visibility.",
      "Delivered tracking systems for 1k+ vehicles and 10k+ events per day.",
      "Integrated notifications and payment flows, handling 1000+ daily transactions.",
    ],
    techStack: [
      "React",
      "Redux",
      "Axios",
      "Chart.js",
      "PostgreSQL",
      "MongoDB",
      "Express",
      "Node.js",
      "jest",
      "webhook",
      "JWT/OAuth",
      "Tailwind CSS",
      "TypeScript",
      "Docker",
      "CI/CD (GitHub Actions)",
      "REST & GraphQL APIs",
    ],
    color: "#101314",
  },
  {
    role: "Software Developer",
    company: "Claimant Mitra",
    duration: "September 2023 - December 2023",
    keyAchievements: [
      "Delivered a full digital platform, replacing manual claim processing.",
      "Built a scalable system for 100+ agents and 1000+ sub-agents.",
      "Set up RBAC and secure authentication for multi-level user permissions.",
    ],
    techStack: [
      "React",
      "Redux",
      "Axios",
      "PostgreSQL",
      "MongoDB",
      "Express",
      "Node.js",
      "JWT/OAuth",
      "Tailwind CSS",
      "TypeScript",
      "Docker",
      "CI/CD (GitHub Actions)",
      "REST & GraphQL APIs",
    ],
    color: "#101314",
  },
];

export default projects;
